version: 1.2
workflows:

  - name: variant-interpretation
    subclass: WDL
    primaryDescriptorPath: /wdl/Relatedness.wdl

  - name: variant-interpretation
    subclass: WDL
    primaryDescriptorPath: /wdl/RunDeNovoSVs.wdl

  - name: variant-interpretation
    subclass: WDL
    primaryDescriptorPath: /wdl/DeNovoSVsScatter.wdl
