version: 1.2
workflows:

  - name: Relatedness
    subclass: WDL
    primaryDescriptorPath: /wdl/Relatedness.wdl

  - name: RunDeNovoSVs
    subclass: WDL
    primaryDescriptorPath: /wdl/RunDeNovoSVs.wdl

  - name: DeNovoSVsScatter
    subclass: WDL
    primaryDescriptorPath: /wdl/DeNovoSVsScatter.wdl
